### ISSUE TITLE
Dockerfile base image outdated?

### ISSUE THREAD

**Issue by test123-all** [dockage/tor-privoxy#11]
Hello,
I noticed that the image of this repository doesn't support the arm64 architecture (raspberry pi). I therefore tried to switch components in the dockerfile to support the arm64 architecture. I noticed that the tor-privoxy image is based on a custom alpine image from dockage too. That image has a  tag that seems to point to a outdated version.

The tor-privoxy dockerfile says: 
`FROM dockage/alpine:3.9-openrc`

At the dockage/alpine repository (see: https://github.com/dockage/alpine 2023.01.31) there isn't the mentioned tag in the "supported" list. But there is a tag `:3-openrc` that seems to pick the latest costum dockage alpine3 image (currently 3.16.2 2023.01.31) that supports openrc.
That image also supports the arm64 architecture and builds correctly on my Raspberry Pi. I tested the tor-proxy with some https requests and the control port with an ip-change. Both work correctly. I wasn't able yet to test other functions or architectures too.

But for now I come to the conclusion that the above mentioned Dockerfile of this tor-privoxy repository line should be changed to:
`FROM dockage/alpine:3-openrc`

Is this correct? If it isn't, why is the tor-privoxy image based on a "old" custom image?

Yours Sincerely

**Comment by mortymacs** [comment]
Hi @test123-all 

Thanks for your report. The issue has been fixed in this PR https://github.com/dockage/tor-privoxy/pull/12

**Comment by test123-all** [comment]
Hey @mortymacs 
No problem :). Also thank you very much for your quick response!
