### ISSUE TITLE
Missing Health Check

### ISSUE THREAD

**Issue by RapidFire05** [dockage/tor-privoxy#18]
Is there a way to add a health check to this image/container? I have done some in the past using curl but I do not want to create a custom image just to add curl in. Is there something in there already that can validate through a check to check.torproject.org? I played around with NC doing this: nc -z -v 127.0.0.1 9050 ...but not sure if that is the best way.

**Comment by mortymacs** [comment]
Hi @RapidFire05 

By this, do you want to only make sure the Tor service is up or all services as well? like Privoxy, etc.

Cheers,
Mort

**Comment by RapidFire05** [comment]
Good question, I suppose it would be good to check that everything is ready. I was looking to do something like this but it adds curl in. Mainly I want to socks port to be ready before I start another service.

```
FROM dockage/tor-privoxy:latest

RUN apk update && \
apk --no-cache add curl

HEALTHCHECK --interval=120s --timeout=30s --retries=3 \
CMD curl --silent --location --socks5-hostname localhost:9050 https://check.torproject.org/?lang=en_US | \
grep -qm1 Congratulations
```

**Comment by mortymacs** [comment]
> Good question, I suppose it would be good to check that everything is ready. I was looking to do something like this but it adds curl in. Mainly I want the socks port to be ready before I start another service.
> 
> 
> 
> ```
> 
> FROM dockage/tor-privoxy:latest
> 
> 
> 
> RUN apk update && \
> 
> apk --no-cache add curl
> 
> 
> 
> HEALTHCHECK --interval=120s --timeout=30s --retries=3 \
> 
> CMD curl --silent --location --socks5-hostname localhost:9050 https://check.torproject.org/?lang=en_US | \
> 
> grep -qm1 Congratulations
> 
> ```

That's a good idea!
Let's test it through the Privoxy service then.
Also, I was thinking maybe we need to use openrc functioanlities to achieve it, something like https://github.com/OpenRC/openrc/blob/master/supervise-daemon-guide.md
What's your idea?

**Comment by RapidFire05** [comment]
Yes that should work, test through privoxy which should route through tor thereby testing both. Let me test with curl and post later. I have never worked with openrc but curl seems more simple.

**Comment by RapidFire05** [comment]
This seems to work.
```
FROM dockage/tor-privoxy:latest

RUN apk update && \
apk --no-cache add curl

HEALTHCHECK --interval=120s --timeout=30s --retries=3 \
CMD curl -sSf -x localhost:8118 https://check.torproject.org | grep -qm1 Congratulations
```

**Comment by mortymacs** [comment]
> This seems to work.
> 
> ```
> 
> FROM dockage/tor-privoxy:latest
> 
> 
> 
> RUN apk update && \
> 
> apk --no-cache add curl
> 
> 
> 
> HEALTHCHECK --interval=120s --timeout=30s --retries=3 \
> 
> CMD curl -sSf -x localhost:8118 https://check.torproject.org | grep -qm1 Congratulations
> 
> ```

Thanks!
So, how can we apply it inside the main image instead of creating an image on top of the main image?
Do you want it to be inside the main image?

**Comment by RapidFire05** [comment]
So ive been going back and forth on the healthcheck in the image or not. curl only adds about 28MB and it would just be 1 line to add to the base dockerfile. Whether or not the healthcheck is included in the base image is debatable as the interval & timeout conditions could be customized based on user preference. health check is easy enough to include in a project's docker compose file. But the underlying image would need curl available to do the checks. 

I think....

```RUN apk --no-cache --update --upgrade add tor privoxy socat \```

could be changed to...

```RUN apk --no-cache --update --upgrade add tor privoxy socat curl \```

But I am not sure what these lines are doing at the end when the services get added again. Would curl need to be down here as well? I am thinking no.

```
&& rc-update add tor \
&& rc-update add privoxy \
&& rc-update add socat
```

**Comment by RapidFire05** [comment]
Going to close it. The info here is enough for users to add a health check if they desire.
