### ISSUE TITLE
ControlPort on 9052, but exposed port on 9051

### ISSUE THREAD

**Issue by amrittb** [dockage/tor-privoxy#4]
Your torrc file configuration changed the ControlPort from 9051 to 9052, however, you are exposing 9051. Can you explain if that is a deliberate choice or a mistake?

**Comment by Parham-sagharchi** [comment]
i have these probel with this image, what should i do?

**Comment by mortymacs** [comment]
@Parham-sagharchi would you please explain what's your problem?

**Comment by Parham-sagharchi** [comment]
> @Parham-sagharchi would you please explain what's your problem?

my problem : [Errno 111] Connection refused

can u help me?

**Comment by CoolDouble** [comment]
Hey. How did you configure a password for the ControlPort?
